language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - redis-server

before_script: composer install -n
before_script: composer require satooshi/php-coveralls --dev

script:
  - mkdir -p build/logs
  - ./vendor/bin/behat
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

after_script: php vendor/bin/coveralls
